version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      SERVICE_NAME: user-service
      MONGO_URI: mongodb://mongo:27017/userdb
      PORT: 3000
      PRODUCT_DOMAIN: http://product-service
      PRODUCT_PORT: 3001
      API_BASE_URL: api
      PRODUCT_VERSION: v2
      PRODUCT_PATH: products
      ENABLE_STRUCTURED_LOGS: true
      LOG_LEVEL: info
      JWT_SECRET: thisIsADrill

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      SERVICE_NAME: product-service
      MONGO_URI: mongodb://mongo:27017/products
      PORT: 3001
      USER_DOMAIN: http://user-service
      USER_PORT: 3000
      API_BASE_URL: api
      USER_VERSION: v2
      USER_PATH: users
      ENABLE_STRUCTURED_LOGS: true
      LOG_LEVEL: info
      JWT_SECRET: thisIsADrill