apiVersion: v1
kind: ConfigMap
metadata:
  name: error-codes
  namespace: my-services
data:
  E400_USER_INVALID_INPUT: "User input is missing or malformed"
  E400_USER_EMAIL_INVALID: "Email format is invalid"
  E400_USER_PASSWORD_WEAK: "Password does not meet complexity requirements"
  E400_USER_FIELD_REQUIRED: "Required user field is missing"
  E400_USER_PROFILE_INCOMPLETE: "User profile is incomplete or missing fields"
  E401_USER_TOKEN_MISSING: "Authentication token is missing"
  E401_USER_TOKEN_EXPIRED: "Authentication token has expired"
  E401_USER_TOKEN_INVALID: "Token is malformed or signature is invalid"
  E403_USER_ACCESS_DENIED: "User lacks permission for the action"
  E403_USER_ROLE_UNAUTHORIZED: "Role is not allowed to access this resource"
  E403_USER_SESSION_REVOKED: "Session was revoked manually (e.g. logout everywhere)"
  E404_USER_NOT_FOUND: "User ID or account does not exist"
  E404_USER_PROFILE_NOT_FOUND: "Profile data for user not found"
  E409_USER_ALREADY_EXISTS: "User account with email/username already exists"
  E409_USER_EMAIL_CONFLICT: "Email is already in use by another account"
  E422_USER_VALIDATION_FAILED: "Business logic validation failed for user input"
  E429_USER_TOO_MANY_ATTEMPTS: "Too many login or password reset attempts"
  E500_USER_DB_ERROR: "Database query or transaction failure"
  E500_USER_HASHING_ERROR: "Password hashing or verification error"
  E500_USER_UNEXPECTED_ERROR: "Catch-all for uncaught errors in user service"
  E502_USER_DEPENDENCY_FAILED: "Upstream service (e.g., email or auth) failed"
  E503_USER_SERVICE_UNAVAILABLE: "Service is down or restarting (healthcheck fail)"
---
# User Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: my-services
data:
  SERVICE_NAME: user-service
  MONGO_URI: "mongodb://user-service-db:27017/userdb"
  PORT: "3000"
  ENABLE_STRUCTURED_LOGS: "true"
  LOG_LEVEL: info
---
# Product Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: my-services
data:
  SERVICE_NAME: product-service
  MONGO_URI: "mongodb://product-service-db:27017/productdb"
  PORT: "3001"
  ENABLE_STRUCTURED_LOGS: "true"
  LOG_LEVEL: info
---
# Web Interface ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-interface-config
  namespace: my-services
data:
  REACT_APP_SERVICE_NAME: web-interface
  REACT_APP_ENABLE_STRUCTURED_LOGS: "true"
  REACT_APP_LOG_LEVEL: info
  REACT_APP_API_BASE_URL: "/api"
  REACT_APP_USER_PATH: "/users"
  REACT_APP_PRODUCT_PATH: "/products"