# Error Codes ConfigMap for System
apiVersion: v1
kind: ConfigMap
metadata:
  name: system-error-codes
  namespace: my-services
data:
  E400_MISSING_TOKEN: "Authentication token is missing"
  E400_MALFORMED_TOKEN: "Authentication token is malformed"
  E401_INVALID_TOKEN: "Authentication token is invalid"
  E401_EXPIRED_TOKEN: "Authentication token is expired"
  E400_USER_EXISTS: "Email already exists"
  E400_USER_NOT_FOUND: "Invalid email"
  E400_INVALID_PASSWORD: "Invalid password"
  E400_INVALID_PRODUCT_ID: "Invalid product ID format"
  E400_CREATE_PRODUCT_FAIL: "Failed to create product"
  E400_UPDATE_PRODUCT_FAIL: "Failed to update product"
  E400_DELETE_PRODUCT_FAIL: "Failed to delete product"
  E404_PRODUCT_NOT_FOUND: "Product not found"
  E500_SERVER_ERROR: "Server error"
  E500_INTENTIONAL_CRASH: "Intentional crash for testing purposes"
---
# Error Codes ConfigMap for Client
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-error-codes
  namespace: my-services
data:
  E400_CLIENT_BAD_TOKEN: "Authentication token is missing or malformed"
  E401_CLIENT_INVALID_TOKEN: "Authentication token is invalid or expired"
  E400_CLIENT_USER_EXISTS: "Email already exists"
  E400_CLIENT_INVALID_CREDENTIALS: "Invalid email or password"
  E400_CLIENT_INVALID_PRODUCT_ID: "Invalid product ID format"
  E400_CLIENT_CREATE_PRODUCT_FAIL: "Failed to create product"
  E400_CLIENT_UPDATE_PRODUCT_FAIL: "Failed to update product"
  E400_CLIENT_DELETE_PRODUCT_FAIL: "Failed to delete product"
  E404_CLIENT_PRODUCT_NOT_FOUND: "Product not found"
  E500_CLIENT_SERVER_ERROR: "Server error"
  E500_CLIENT_INTENTIONAL_CRASH: "Intentional crash for testing purposes"
---
# User Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: my-services
data:
  SERVICE_NAME: user-service
  MONGO_URI: "mongodb://user-service-db:27017/userdb"
  PORT: "3000"
  ENABLE_STRUCTURED_LOGS: "true"
  LOG_LEVEL: info
---
# Product Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: my-services
data:
  SERVICE_NAME: product-service
  MONGO_URI: "mongodb://product-service-db:27017/productdb"
  PORT: "3001"
  ENABLE_STRUCTURED_LOGS: "true"
  LOG_LEVEL: info
---
# Web Interface ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-interface-config
  namespace: my-services
data:
  REACT_APP_SERVICE_NAME: web-interface
  REACT_APP_ENABLE_STRUCTURED_LOGS: "true"
  REACT_APP_LOG_LEVEL: info
  REACT_APP_API_BASE_URL: "api"
  REACT_APP_USER_PATH: "users"
  REACT_APP_USER_VERSION: "v2"
  REACT_APP_PRODUCT_PATH: "products"
  REACT_APP_PRODUCT_VERSION: "v2"