apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-messages
data:
  INVALID_CREDENTIALS: "Invalid email or password"
  VALIDATION_ERROR:  "Email and password are required"
---
# User Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "3000"
  MONGO_URI: "mongodb://user-service-db:27017/usersdb"
---
# Product Service ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  PORT: "3001"
  MONGO_URI: "mongodb://product-service-db:27017/productdb"
---
# Web Interface ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-interface-config
data:
  REACT_APP_USER_SERVICE: "/users"
  REACT_APP_PRODUCT_SERVICE: "/products"