apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface
  template:
    metadata:
      labels:
        app: user-interface
    spec:
      containers:
        - name: user-interface
          image: user-interface:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
