services:
  product-service:
    image: product-service:latest
    build: .
    ports:
      - "3101:3001"
    environment:
      - MONGO_URI=mongodb://product-service-db:27018/productdb
    depends_on:
      - product-service-db
    restart: always

  product-service-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local