services:
  product-service:
    image: product-service:latest
    build: .
    ports:
      - "3301:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    # ports:
    #   - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local