version: '3.8'
services:
  product-service:
    image: product-service:latest
    build: .
    ports:
      - "3302:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local