apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-db-pvc
spec:
  accessModes:
    - ReadWriteOnce            # only one Pod may write at a time
  resources:
    requests:
      storage: 100Mi           # how much disk you need
  storageClassName: hostpath   # your cluster’s default provisioner
