apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-interface
  namespace: my-services
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-interface
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-interface
    spec:
      containers:
        - name: web-interface
          image: web-interface:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
