apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: my-services
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: product-service
  ports:
    - port: 3001
      targetPort: 3001
      # nodePort: 30001