apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-configuration
  namespace: my-services
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    # - host: localhost
    - http:
        paths:
        # Paths for user service
        - path: /api/v1/users
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 3000
        - path: /api/v2/users
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 3000
        # Path for product service
        - path: /api/v1/products
          pathType: Prefix
          backend:
            service:
              name: product-service
              port:
                number: 3001
        - path: /api/v2/products
          pathType: Prefix
          backend:
            service:
              name: product-service
              port:
                number: 3001
        # Path for product service
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web-interface
              port:
                number: 80