name: CI for User Service

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # services:
    #   mongo:
    #     image: mongo
    #     ports:
    #       - 27017:27017

    # env:
    #   MONGO_URI: mongodb://localhost:27017/user-test-db

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # Optional: build Docker image
    # - name: Build Docker image
    #   run: docker build -t user-service .
