services:
  user-service:
    image: user-service:latest
    build: .
    ports:
      - "3100:3000"
    environment:
      - MONGO_URI=mongodb://user-service-db:27017/userdb
      - JWT_SECRET=ThomasIsGreat
    depends_on:
      - user-service-db
    restart: always

  user-service-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local