apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: my-services
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: user-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
