apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: my-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: user-service-config
            - configMapRef:
                name: error-codes
            - secretRef:
                name: user-service-secret
