name: Integration Test (User Profile Deletion)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports: [27017:27017]
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install root dependencies
      run: npm install

    - name: Build and Start Services
      run: docker-compose up -d --build

    - name: Wait for user-service
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:3000/api/v2/users/all; then
            echo "user-service is ready"
            break
          fi
          echo "Waiting for user-service..."
          sleep 5
        done

    - name: Wait for product-service
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:3001/api/v2/products/all; then
            echo "product-service is ready"
            break
          fi
          echo "Waiting for product-service..."
          sleep 5
        done

    - name: Run integration tests with Jest
      run: npx jest __tests__/integration-delete-user-products.test.js --detectOpenHandles --forceExit
      env:
        NODE_ENV: test