# User Service Secret
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  PORT: "3000"
  MONGO_URI: "mongodb://user-service-db:27017/usersdb"
  JWT_SECRET: "ThomasIsGreat"
---
# Product Service Secret
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
stringData:
  PORT: "3001"
  MONGO_URI: "mongodb://product-service-db:27017/productdb"
---
# Web Interface Secret
apiVersion: v1
kind: Secret
metadata:
  name: web-config-secret
type: Opaque
stringData:
  REACT_APP_USER_SERVICE: "/users"
  REACT_APP_PRODUCT_SERVICE: "/products"
