# secret-all.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  PORT: "3000"
  MONGO_URI: "mongodb://mongo:27017/usersdb"
  JWT_SECRET: "ThomasIsGreat"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
stringData:
  PORT: "3001"
  MONGO_URI: "mongodb://mongo:27017/productdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: web-config-secret
type: Opaque
stringData:
  REACT_APP_USER_SERVICE: "/users"
  REACT_APP_PRODUCT_SERVICE: "/products"
